mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lishi.moduledb.domain
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/dragon?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
